using Microsoft.AspNetCore.Identity;
using Ortakare.Api.Features.Auth.Login;
using Ortakare.Api.Features.Auth.Logout;
using Ortakare.Api.Features.Auth.Refresh;
using Ortakare.Api.Features.Auth.Register;
using Ortakare.Api.Features.Dashboard.GetOwnerDashboardSummary;
using Ortakare.Api.Features.Dashboard.GetOwnerRecentActivity;
using Ortakare.Api.Features.Dashboard.GetOwnerStorageBreakdown;
using Ortakare.Api.Features.Dashboard.GetOwnerStorageQuota;
using Ortakare.Api.Features.EventAudit;
using Ortakare.Api.Features.EventAudit.GetEventAuditLogs;
using Ortakare.Api.Features.EventAudit.Handlers;
using Ortakare.Api.Features.Events.CloseEvent;
using Ortakare.Api.Features.Events.CreateEvent;
using Ortakare.Api.Features.Events.DeleteEvent;
using Ortakare.Api.Features.Events.DomainEvents;
using Ortakare.Api.Features.Events.GetEvent;
using Ortakare.Api.Features.Events.GetEventRecentActivity;
using Ortakare.Api.Features.Events.GetEventSummary;
using Ortakare.Api.Features.Events.GetMyEvents;
using Ortakare.Api.Features.Events.RegenerateGalleryToken;
using Ortakare.Api.Features.Events.ReopenEvent;
using Ortakare.Api.Features.Events.UpdateEvent;
using Ortakare.Api.Features.GalleryExports.CancelPendingGalleryExport;
using Ortakare.Api.Features.GalleryExports.CreateGalleryExport;
using Ortakare.Api.Features.GalleryExports.DeleteGalleryExport;
using Ortakare.Api.Features.GalleryExports.GetEventExports;
using Ortakare.Api.Features.GalleryExports.GetGalleryExport;
using Ortakare.Api.Features.GalleryExports.RetryFailedGalleryExport;
using Ortakare.Api.Features.Notifications;
using Ortakare.Api.Features.Notifications.DeleteNotification;
using Ortakare.Api.Features.Notifications.GetMyNotifications;
using Ortakare.Api.Features.Notifications.GetUnreadNotificationCount;
using Ortakare.Api.Features.Notifications.Handlers;
using Ortakare.Api.Features.Notifications.MarkAllNotificationsAsRead;
using Ortakare.Api.Features.Notifications.MarkNotificationAsRead;
using Ortakare.Api.Features.Participants;
using Ortakare.Api.Features.Participants.BlockEventParticipant;
using Ortakare.Api.Features.Participants.DeleteEventParticipant;
using Ortakare.Api.Features.Participants.DomainEvents;
using Ortakare.Api.Features.Participants.GetEventParticipants;
using Ortakare.Api.Features.Participants.JoinEvent;
using Ortakare.Api.Features.Participants.UnblockEventParticipant;
using Ortakare.Api.Features.Participants.UpdateParticipantDisplayName;
using Ortakare.Api.Features.Photos.DeleteGuestPhoto;
using Ortakare.Api.Features.Photos.DeleteOwnerPhoto;
using Ortakare.Api.Features.Photos.DomainEvents;
using Ortakare.Api.Features.Photos.GetEventPhotos;
using Ortakare.Api.Features.Photos.UploadPhoto;
using Ortakare.Api.Features.PublicEvents.GetPublicEvent;
using Ortakare.Api.Features.Storage;
using Ortakare.Api.Features.Storage.GetEventStorageTrend;
using Ortakare.Api.Features.Storage.GetParticipantStorageBreakdown;
using Ortakare.Api.Features.Storage.GetParticipantStorageDetail;
using Ortakare.Api.Features.Storage.GetStorageUsageTrend;
using Ortakare.Api.Features.Storage.GetUploadPolicy;
using Ortakare.Api.Features.Storage.ValidateUpload;
using Ortakare.Api.Features.System.Health;
using Ortakare.Api.Features.Users;
using Ortakare.Api.Infrastructure.Authentication;
using Ortakare.Api.Infrastructure.BackgroundJobs;
using Ortakare.Api.Infrastructure.DomainEvents;
using Ortakare.Api.Infrastructure.Outbox;

namespace Ortakare.Api.Extensions;

public static class FeatureServiceRegistration
{
    public static IServiceCollection AddFeatureHandlers(this IServiceCollection services)
    {
        services.AddScoped<GetHealthHandler>();
        services.AddScoped<RegisterHandler>();
        services.AddScoped<LoginHandler>();
        services.AddScoped<RefreshHandler>();
        services.AddScoped<LogoutHandler>();
        services.AddScoped<GetOwnerDashboardSummaryHandler>();
        services.AddScoped<GetOwnerRecentActivityHandler>();
        services.AddScoped<GetOwnerStorageBreakdownHandler>();
        services.AddScoped<GetOwnerStorageQuotaHandler>();
        services.AddScoped<EventAuditWriter>();
        services.AddScoped<GetEventAuditLogsHandler>();
        services.AddScoped<NotificationOutboxWriter>();
        services.AddScoped<GetUnreadNotificationCountHandler>();
        services.AddScoped<GetMyNotificationsHandler>();
        services.AddScoped<MarkNotificationAsReadHandler>();
        services.AddScoped<MarkAllNotificationsAsReadHandler>();
        services.AddScoped<DeleteNotificationHandler>();
        services.AddScoped<IDomainEventDispatcher, DomainEventDispatcher>();
        services.AddScoped<IDomainEventHandler<EventClosedDomainEvent>, EventClosedAuditHandler>();
        services.AddScoped<IDomainEventHandler<EventReopenedDomainEvent>, EventReopenedAuditHandler>();
        services.AddScoped<IDomainEventHandler<ParticipantBlockedDomainEvent>, ParticipantBlockedAuditHandler>();
        services.AddScoped<IDomainEventHandler<ParticipantUnblockedDomainEvent>, ParticipantUnblockedAuditHandler>();
        services.AddScoped<IDomainEventHandler<ParticipantJoinedDomainEvent>, ParticipantJoinedAuditHandler>();
        services.AddScoped<IDomainEventHandler<ParticipantJoinedDomainEvent>, ParticipantJoinedNotificationHandler>();
        services.AddScoped<IDomainEventHandler<PhotoUploadedDomainEvent>, PhotoUploadedAuditHandler>();
        services.AddScoped<IDomainEventHandler<PhotoUploadedDomainEvent>, PhotoUploadedNotificationHandler>();
        services.AddScoped<StorageUploadPolicyService>();
        services.AddScoped<GetUploadPolicyHandler>();
        services.AddScoped<GetStorageUsageTrendHandler>();
        services.AddScoped<GetEventStorageTrendHandler>();
        services.AddScoped<GetParticipantStorageBreakdownHandler>();
        services.AddScoped<GetParticipantStorageDetailHandler>();
        services.AddScoped<ValidateUploadHandler>();
        services.AddScoped<CreateEventHandler>();
        services.AddScoped<GetMyEventsHandler>();
        services.AddScoped<GetEventHandler>();
        services.AddScoped<GetEventSummaryHandler>();
        services.AddScoped<GetEventRecentActivityHandler>();
        services.AddScoped<UpdateEventHandler>();
        services.AddScoped<CloseEventHandler>();
        services.AddScoped<ReopenEventHandler>();
        services.AddScoped<RegenerateGalleryTokenHandler>();
        services.AddScoped<DeleteEventHandler>();
        services.AddScoped<GetPublicEventHandler>();
        services.AddScoped<JoinEventHandler>();
        services.AddScoped<GetEventParticipantsHandler>();
        services.AddScoped<UpdateParticipantDisplayNameHandler>();
        services.AddScoped<DeleteEventParticipantHandler>();
        services.AddScoped<BlockEventParticipantHandler>();
        services.AddScoped<UnblockEventParticipantHandler>();
        services.AddScoped<UploadPhotoHandler>();
        services.AddScoped<GetEventPhotosHandler>();
        services.AddScoped<DeleteOwnerPhotoHandler>();
        services.AddScoped<DeleteGuestPhotoHandler>();
        services.AddScoped<CreateGalleryExportHandler>();
        services.AddScoped<GetGalleryExportHandler>();
        services.AddScoped<GetEventExportsHandler>();
        services.AddScoped<RetryFailedGalleryExportHandler>();
        services.AddScoped<DeleteGalleryExportHandler>();
        services.AddScoped<CancelPendingGalleryExportHandler>();
        services.AddScoped<BuildGalleryExportJob>();

        services.Configure<OutboxProcessingOptions>(_ => { });
        services.AddScoped<OutboxProcessor>();
        services.AddScoped<OutboxDeliveryDispatcher>();
        services.AddSingleton<IOutboxDeliveryChannel, LoggingOutboxDeliveryChannel>();
        services.AddHostedService<OutboxProcessingWorker>();

        services.AddScoped<IPasswordHasher<User>, PasswordHasher<User>>();
        services.AddSingleton<IAccessTokenService, JwtAccessTokenService>();
        services.AddSingleton<IRefreshTokenService, RefreshTokenService>();
        services.AddSingleton(TimeProvider.System);
        services.AddSingleton<ParticipantTokenService>();
        services.AddSingleton<ImageFileInspector>();
        services.AddHttpContextAccessor();
        services.AddScoped<ICurrentUser, HttpCurrentUser>();

        return services;
    }
}